name: app_initializer_generator
description: App init generator Dart libraries.
version: 1.0.0
homepage: https://github.com/aymtools/flutter-tools

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dependencies:
#  flutter:
#    sdk: flutter
  source_gen: ^0.9.4+4
  dart_style: ^1.0.0
  mustache4dart: ^3.0.0-dev.1.0
  app_initializer:
      path: ../app-initializer
  bean_factory_generator:
    path: ../../flutter-bean-factory/bean-factory-generator

dev_dependencies:

#flutter:
#  uses-material-design: true