name: aym_router_generator
description: AYMRouter generator Dart libraries.
  A flutter routing generator that automatically generates routing tables when compiling. Need to use with aym_router.
version: 1.0.1
homepage: https://github.com/aymtools/flutter-tools

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dependencies:
#  flutter:
#    sdk: flutter
  analyzer: ">=0.39.0 <0.40.0"
  build: ^1.0.0
  source_gen: ^0.9.4+4
  mustache4dart: ^3.0.0-dev.1.0
  aym_router: ^1.0.0
  bean_factory: ^1.0.0
  bean_factory_generator: ^1.0.0

dev_dependencies:
  build_runner: ^1.1.1

#flutter:
#  uses-material-design: true