name: aym_router
description: AYMRouter Dart libraries.A flutter routing generator that automatically generates routing tables when compiling. Need to use with aym_router_generator.
version: 1.2.0
homepage: https://github.com/aymtools/flutter-tools

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dependencies:
  bean_factory: ^1.1.2
#  bean_factory:
#    path: ../../flutter-bean-factory/bean-factory
#  flutter:
#    sdk: flutter

dev_dependencies:

flutter:
  uses-material-design: true