name: app_initializer
description: App init core Dart libraries.
version: 1.0.0
homepage: https://github.com/aymtools/flutter-tools

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dependencies:
#  flutter:
#    sdk: flutter
  source_gen: ^0.9.4+4
  mustache4dart: ^3.0.0-dev.1.0
  bean_factory: ^1.2.0
#      path: ../../flutter-bean-factory/bean-factory

dev_dependencies:

#flutter:
#  uses-material-design: true